# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Karim Abdel Hamid's Blog
email: karimah@aucegypt.edu
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Karim's Blog! Here, we'll take about Computer Graphics, Game Engines, Web Design, and general Computer Science, as well as any other thoughts I might have.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://karimio.github.io" # the base hostname & protocol for your site
twitter_username: karim_abdel_h
github_username:  karimio

# Build settings
markdown: kramdown
